# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x07\x65xample\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"X\n\x0fGetBookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1b\n\x13\x64\x61te_of_publication\x18\x04 \x01(\t\"\x14\n\x12GetAllBooksRequest\">\n\x13GetAllBooksResponse\x12\'\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x18.example.GetBookResponse2\x8e\x01\n\x04\x42ook\x12<\n\x07GetBook\x12\x17.example.GetBookRequest\x1a\x18.example.GetBookResponse\x12H\n\x0bGetAllBooks\x12\x1b.example.GetAllBooksRequest\x1a\x1c.example.GetAllBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKREQUEST']._serialized_start=23
  _globals['_GETBOOKREQUEST']._serialized_end=51
  _globals['_GETBOOKRESPONSE']._serialized_start=53
  _globals['_GETBOOKRESPONSE']._serialized_end=141
  _globals['_GETALLBOOKSREQUEST']._serialized_start=143
  _globals['_GETALLBOOKSREQUEST']._serialized_end=163
  _globals['_GETALLBOOKSRESPONSE']._serialized_start=165
  _globals['_GETALLBOOKSRESPONSE']._serialized_end=227
  _globals['_BOOK']._serialized_start=230
  _globals['_BOOK']._serialized_end=372
# @@protoc_insertion_point(module_scope)
